### ISSUE TITLE
Build failure with PG11: pglogical_output_plugin.h:20:10: fatal error: pglogical_compat.h: No such file or directory

### ISSUE THREAD

**Issue by ChristophBerg** [2ndQuadrant/pglogical#170]
pglogical fails to build against PG 11beta1:
```
21:47:51 make[2]: Entering directory '/<<PKGBUILDDIR>>/build-11'
21:47:51 sed 's/__PGLOGICAL_VERSION__/2.2.0/;s/__REQUIRES__//' /<<PKGBUILDDIR>>/pglogical.control.in > /<<PKGBUILDDIR>>/pglogical.control
21:47:51 gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fdebug-prefix-map=/build/postgresql-11-LcCi7f/postgresql-11-11~beta1=. -fstack-protector-strong -Wformat -Werror=format-security -fno-omit-frame-pointer -fPIC -fPIC -I/usr/include/postgresql -I -Werror=implicit-function-declaration -I. -I/<<PKGBUILDDIR>> -I/usr/include/postgresql/11/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pglogical_apply.o /<<PKGBUILDDIR>>/pglogical_apply.c
21:47:51 In file included from /<<PKGBUILDDIR>>/pglogical_proto_native.h:20:0,
21:47:51                  from /<<PKGBUILDDIR>>/pglogical_conflict.h:22,
21:47:51                  from /<<PKGBUILDDIR>>/pglogical_apply.c:62:
21:47:51 /<<PKGBUILDDIR>>/pglogical_output_plugin.h:20:10: fatal error: pglogical_compat.h: No such file or directory
21:47:51  #include "pglogical_compat.h"
21:47:51           ^~~~~~~~~~~~~~~~~~~~
21:47:51 compilation terminated.
21:47:51 make[2]: *** [<builtin>: pglogical_apply.o] Error 1
```

**Comment by mbanck** [comment]
Now that PostgreSQL11 is at RC1, this is getting more urgent.

**Comment by ringerc** [comment]
I've pushed commit 8328c3ab21762158908ce0f89d9a72c23e6408d7 with initial pglogial2 support for PostgreSQL 11.

Please feel free to report any issues.

**Comment by mbanck** [comment]
Thanks @ringerc, I had to add two more changes to `compat11/pglogical_compat.h` to get it working here, though:

1. Add `#include "replication/origin.h"`

2. Add 

```
#define ExecBRDeleteTriggers(estate, epqstate, relinfo, tupleid, fdw_trigtuple) \
 	ExecBRDeleteTriggers(estate, epqstate, relinfo, tupleid, fdw_trigtuple, NULL)
```

(it is guarded by `#ifdef PG2Q` in  8328c3ab)

The latter is needed due to https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=0527df732beb8c2d584c7e4ea5aeb05cf92e14a2

**Comment by ringerc** [comment]
It now builds against current Pg11 HEAD. What a silly mistake on my part. This is what comes of having too many remotes and not having time to follow core development properly anymore.

**Comment by mbanck** [comment]
I still get the first issue:

```
sed 's/__PGLOGICAL_VERSION__/2.2.0/;s/__REQUIRES__//' /home/mba/debian/pkg-postgresql/git/pglogical/pglogical.control.in > /home/mba/debian/pkg-postgresql/git/pglogical/pglogical.control
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -fPIC -fPIC -I/home/mba/tmp/include -I/home/mba/debian/pkg-postgresql/git/pglogical/compat11 -Werror=implicit-function-declaration -I. -I./ -I/home/mba/tmp/include/postgresql/server -I/home/mba/tmp/include/postgresql/internal  -D_GNU_SOURCE   -c -o pglogical_proto_json.o pglogical_proto_json.c -MMD -MP -MF .deps/pglogical_proto_json.Po
pglogical_proto_json.c: In function 'pglogical_json_write_begin':
pglogical_proto_json.c:59:24: error: 'InvalidRepOriginId' undeclared (first use in this function)
  if (txn->origin_id != InvalidRepOriginId)
                        ^~~~~~~~~~~~~~~~~~
pglogical_proto_json.c:59:24: note: each undeclared identifier is reported only once for each function it appears in
/home/mba/tmp/lib/postgresql/pgxs/src/makefiles/../../src/Makefile.global:878: recipe for target 'pglogical_proto_json.o' failed
make: *** [pglogical_proto_json.o] Error 1
```

I just tried in a Debian unstable chroot (which switched to v11 recently) and it fails in the same way.

**Comment by ringerc** [comment]
I see what's happening there, looking

**Comment by ringerc** [comment]
Fixed by 856fbf7
